spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  grpc:
    server:
      port: 9090
      address: 0.0.0.0