spring:
  application:
    name: Order service
  jpa:
    hibernate.ddl-auto: none # TODO: set to none once flyway integration is finished
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_URL}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  grpc:
    server:
      port: 9090
      address: 0.0.0.0


order:
  repository:
    type: db
  payment-client:
    type: kafka
  event-publisher:
    type: kafka
  id-generator:
    type: random

kafka:
  topic:
    payment-processed-succeeded: payment-processed-succeeded
    payment-processed-failed: payment-processed-failed
    payment-request: payment-request
    order-status-updated: order-status-updated
    cart-event: cart-event

grpc:
  server:
    port: 9090
    security:
      enabled: false # Set to true to enable TLS
