spring:
  kafka:
    bootstrap-servers: localhost:9092
#  flyway:
#    enabled: false

order:
  repository:
    type: in-memory
  payment-client:
    type: in-memory
  event-publisher:
    type: in-memory