spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service-db
    username: admin
    password: admin


order:
  repository:
    type: db
  payment-client:
    type: in-memory
  event-publisher:
    type: in-memory

server:
  port: 8300