spring:
  datasource:
    url: jdbc:postgresql://order-service-db:5432/order-service-db
  kafka:
    bootstrap-servers: kafka:9092

grpc:
  server:
    security:
      enabled: false # Set to true to enable TLS
  client:
    product-service:
      address: static://product-service:50051
      negotiationType: plaintext
